import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsNotEmpty, IsNumber, IsOptional, IsString } from 'class-validator';

export default class DispatchB2PochiPayoutDto {
  @ApiProperty({
    example: '600997_Test_32et3241ed8yu',
    description: 'Unique request identifier generated by the merchant for every B2Pochi disbursement.',
  })
  @IsString()
  @IsNotEmpty()
  OriginatorConversationID: string = '';

  @ApiProperty({
    example: 'BusinessPayToPochi',
    description: 'M-Pesa command ID for B2Pochi disbursement. Use BusinessPayToPochi.',
  })
  @IsString()
  @IsNotEmpty()
  CommandID: string = 'BusinessPayToPochi';

  @ApiProperty({
    example: '10',
    description: 'Amount to disburse to the customer business wallet in KES.',
  })
  @IsNotEmpty()
  Amount: string | number = '10';

  @ApiProperty({
    example: 254705912645,
    description: 'Customer mobile number receiving the disbursement, without the + sign.',
  })
  @IsNumber()
  @IsNotEmpty()
  PartyB: number = 0;

  @ApiProperty({
    example: 'remarked',
    description: 'Remarks sent along with the B2Pochi disbursement request.',
  })
  @IsString()
  @IsNotEmpty()
  Remarks: string = '';

  @ApiProperty({
    example: 'https://mydomain.com/b2c/timedout',
    description: 'URL M-Pesa calls when the payment request times out while awaiting processing.',
  })
  @IsString()
  @IsNotEmpty()
  QueueTimeOutURL: string = '';

  @ApiProperty({
    example: 'https://mydomain.com/b2c/result',
    description: 'URL M-Pesa calls after processing the payment request.',
  })
  @IsString()
  @IsNotEmpty()
  ResultURL: string = '';

  @ApiPropertyOptional({
    example: 'ChristmasPay',
    description: 'Optional occasion field for extra transaction metadata.',
  })
  @IsString()
  @IsOptional()
  Occassion?: string;
}
