import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsNotEmpty, IsNumber, IsOptional, IsString, IsUrl } from 'class-validator';

export default class DispatchB2CPayoutDto {
  @ApiProperty({
    example: '600997_Test_32et3241ed8yu',
    description: 'Unique request identifier generated by the merchant for every B2C disbursement.',
  })
  @IsString()
  @IsNotEmpty()
  OriginatorConversationID: string = '';

  @ApiProperty({
    example: 'BusinessPayment',
    enum: ['SalaryPayment', 'BusinessPayment', 'PromotionPayment'],
    description: 'B2C transaction type supported by the M-Pesa account.',
  })
  @IsString()
  @IsNotEmpty()
  CommandID: string = 'BusinessPayment';

  @ApiProperty({ example: 10, description: 'Amount to disburse in KES.' })
  @IsNumber()
  @IsNotEmpty()
  Amount: number = 0;

  @ApiProperty({ example: 254705912645, description: 'Customer MSISDN in international format without a plus sign.' })
  @IsNumber()
  @IsNotEmpty()
  PartyB: number = 0;

  @ApiProperty({ example: 'Salary payment', description: 'Additional transaction information, 2-100 characters.' })
  @IsString()
  @IsNotEmpty()
  Remarks: string = '';

  @ApiPropertyOptional({ example: 'https://mydomain.com/payments/callbacks/mpesa', description: 'URL used for both B2C result and timeout notifications. Defaults to MPESA_CALLBACK_URL plus /callbacks/mpesa.' })
  @IsUrl()
  @IsOptional()
  callbackUrl?: string;

  @ApiPropertyOptional({ example: 'ChristmasPay', description: 'Optional additional transaction information.' })
  @IsString()
  @IsOptional()
  Occassion?: string;
}
