import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsNotEmpty, IsNumber, IsOptional, IsString, Min } from 'class-validator';

export class KcbFundsTransferDto {
  @ApiProperty({ example: 'JOHN DOE', description: 'Beneficiary name as registered by the receiving bank.' })
  @IsString()
  @IsNotEmpty()
  beneficiaryDetails = '';

  @ApiPropertyOptional({ example: 'KE0010001', description: 'KCB company code. Defaults to KCB_COMPANY_CODE when omitted.' })
  @IsString()
  @IsOptional()
  companyCode?: string;

  @ApiProperty({ example: '1279287799', description: 'Beneficiary account number.' })
  @IsString()
  @IsNotEmpty()
  creditAccountNumber = '';

  @ApiProperty({ example: 'KES', description: 'Transfer currency.' })
  @IsString()
  @IsNotEmpty()
  currency = 'KES';

  @ApiPropertyOptional({ example: '1279258233', description: 'Debit account. Defaults to KCB_DEBIT_ACCOUNT_NUMBER when omitted.' })
  @IsString()
  @IsOptional()
  debitAccountNumber?: string;

  @ApiProperty({ example: 26, description: 'Amount to transfer.' })
  @IsNumber()
  @Min(0.01)
  debitAmount = 0;

  @ApiProperty({ example: 'UT Fund withdrawal', description: 'Business description of the transfer.' })
  @IsString()
  @IsNotEmpty()
  paymentDetails = '';

  @ApiProperty({ example: 'FT1234567890', description: 'Unique transfer reference generated by the calling system.' })
  @IsString()
  @IsNotEmpty()
  transactionReference = '';

  @ApiProperty({ example: 'IF', description: 'KCB funds transfer transaction type.' })
  @IsString()
  @IsNotEmpty()
  transactionType = 'IF';

  @ApiProperty({ example: '01', description: 'Beneficiary bank code.' })
  @IsString()
  @IsNotEmpty()
  beneficiaryBankCode = '';
}